# Generated by Django 6.1.1 on 2026-09-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('desarrollador', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('plataforma', models.CharField(max_length=200)),
                ('anio_lanzamiento', models.IntegerField(verbose_name='Año de lanzamiento')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
