# Generated by Django 6.1.1 on 2026-09-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_empresa_franquicia_genero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'verbose_name_plural': 'Reseñas'},
        ),
    ]
