# Generated by Django 6.1.1 on 2026-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_alter_perfil_options_alter_resena_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquicia',
            name='imagen',
            field=models.URLField(default='https://example.com/imagen.jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.URLField(default='https://example.com/imagen.jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
