# Generated by Django 6.1.1 on 2026-10-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_franquicia_imagen_juego_imagen_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='franquicia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
