# Generated by Django 6.1.1 on 2026-10-08 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0005_alter_empresa_nombre_alter_franquicia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='director_ejecutivo',
            field=models.CharField(max_length=200, verbose_name='director ejecutivo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='localizacion',
            field=models.CharField(max_length=200, verbose_name='localización'),
        ),
        migrations.AlterField(
            model_name='franquicia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(verbose_name='Fecha de Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='biografía'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='juego_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.juego', verbose_name='Juego favorito'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='plataforma_favorita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.plataforma', verbose_name='Plataforma favorita'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='puntuacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación'),
        ),
    ]
