# Generated by Django 6.1.1 on 2026-10-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0006_alter_empresa_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='anio_fundacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='director_ejecutivo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='localizacion',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='fecha_lanzamiento',
        ),
    ]
